version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo hahahha
      - $(aws ecr get-login --no-include-email --region ap-southeast-1) 
  build:
    commands:
      - docker build -t simple-php .
      - docker tag simple-php 666054393290.dkr.ecr.ap-southeast-1.amazonaws.com/php-repo
  post_build:
    commands: 
      - docker push 666054393290.dkr.ecr.ap-southeast-1.amazonaws.com/php-repo  
      - printf '{"ImageURI":"%s"}' 666054393290.dkr.ecr.ap-southeast-1.amazonaws.com/php-repo:simple-php > imageDetail.json
artifacts:
  files:
    - imageDetail.json
